networks:
  main:
    name: bts-assetdb

services:
  database:
    image: mariadb:10.4
    container_name: bts-assetdb-database
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: asset_register
      MYSQL_ROOT_PASSWORD: developer
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 60s
      timeout: 5s
      retries: 3
    volumes: 
      - ./local/database:/var/lib/mysql
    restart: no
    networks:
      - main

  mail:
    image: djfarrelly/maildev
    container_name: bts-assetdb-mail
    ports:
      - '8081:80'
      - '1025:25'
    restart: no
    networks:
      - main

  