networks:
  main:
    name: bts-assetdb

services:
  database:
    image: mariadb:10.4
    container_name: bts-assetdb-database
    networks:
      - main
    ports:
      - '6021:3306'
    environment:
      MYSQL_DATABASE: asset_register
      MYSQL_ROOT_PASSWORD: developer
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 60s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  mail:
    image: djfarrelly/maildev
    container_name: bts-assetdb-mail
    networks:
      - main
    ports:
      - '6022:80'
    restart: unless-stopped

  site:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: bts-assetdb-site
    networks:
      - main
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
      mail:
        condition: service_started
    restart: unless-stopped
