apiVersion: v1
kind: Service
metadata:
  name: {{ include "asset-database.fullname" . }}
  labels:
    {{- include "asset-database.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "asset-database.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "asset-database.fullname" . }}
  labels:
    {{- include "asset-database.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-http-to-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "asset-database.fullname" . }}
                port:
                  number: 8000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ include "asset-database.fullname" . }}-tls
