apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "asset-database.fullname" . }}
  labels:
    {{- include "asset-database.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: aws-ssm
  refreshInterval: 15m
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: /backstage/{{ .Values.environment }}/asset-database/secret-key
    - secretKey: DB_USER
      remoteRef:
        key: /backstage/{{ .Values.environment }}/asset-database/db-credentials
        property: username
    - secretKey: DB_PASS
      remoteRef:
        key: /backstage/{{ .Values.environment }}/asset-database/db-credentials
        property: password
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: /backstage/{{ .Values.environment }}/asset-database/smtp-credentials
        property: username
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: /backstage/{{ .Values.environment }}/asset-database/smtp-credentials
        property: password
