# Generated by Django 3.0.3 on 2020-06-24 14:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=15)),
                ('make', models.CharField(blank=True, max_length=32, null=True)),
                ('model', models.CharField(blank=True, max_length=32, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=32, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('is_identifiable', models.BooleanField()),
                ('is_location', models.BooleanField()),
                ('is_multichannel', models.BooleanField()),
                ('is_channel', models.BooleanField()),
                ('is_consumable', models.BooleanField()),
                ('is_archived', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('site', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=15)),
                ('testcode_1', models.CharField(max_length=10)),
                ('testcode_2', models.CharField(max_length=10)),
                ('machine_serial_no', models.CharField(max_length=8)),
                ('machine_firmware_version', models.CharField(max_length=6)),
                ('retest_freq_months', models.IntegerField()),
                ('user_data_input_order', models.CharField(max_length=12)),
                ('item_make', models.CharField(blank=True, max_length=20, null=True)),
                ('item_model', models.CharField(blank=True, max_length=20, null=True)),
                ('item_description', models.CharField(blank=True, max_length=20, null=True)),
                ('item_notes', models.CharField(blank=True, max_length=20, null=True)),
                ('item_group', models.CharField(blank=True, max_length=20, null=True)),
                ('item_serial_number', models.CharField(blank=True, max_length=20, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bts_asset_db.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('initials', models.CharField(max_length=10, unique=True)),
                ('pat_level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('vis_level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('machine_name', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('alt_machine_name', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisualTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('failed', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bts_asset_db.Item')),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'vis_level': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visual_supervision_set', to='bts_asset_db.Tester')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_test_set', to='bts_asset_db.Tester')),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.IntegerField()),
                ('test_parameter_1', models.CharField(blank=True, max_length=5, null=True)),
                ('test_parameter_2', models.CharField(blank=True, max_length=18, null=True)),
                ('test_parameter_3', models.CharField(blank=True, max_length=6, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bts_asset_db.Records')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bts_asset_db.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Repairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('failed', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bts_asset_db.Item')),
                ('repairer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_set', to='bts_asset_db.Tester')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_supervision_set', to='bts_asset_db.Tester')),
            ],
        ),
        migrations.AddField(
            model_name='records',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bts_asset_db.Tester'),
        ),
        migrations.CreateModel(
            name='ItemClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bts_asset_db.Subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='associations',
            field=models.ManyToManyField(blank=True, related_name='associated_item_set', to='bts_asset_db.ItemClass'),
        ),
        migrations.AddField(
            model_name='item',
            name='itemclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_item_set', to='bts_asset_db.ItemClass'),
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bts_asset_db.Owner'),
        ),
        migrations.AddField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_set', to='bts_asset_db.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_item_set', to='bts_asset_db.Item'),
        ),
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bts_asset_db.Department'),
        ),
    ]
