# Generated by Django 3.0.3 on 2020-02-18 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('record_id', models.IntegerField(db_column='Record ID', primary_key=True, serialize=False)),
                ('item_id', models.CharField(blank=True, db_column='Item ID', max_length=15, null=True)),
                ('timestamp', models.DateField(blank=True, db_column='Timestamp', null=True)),
                ('site', models.CharField(blank=True, db_column='Site', max_length=15, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=15, null=True)),
                ('tester', models.CharField(blank=True, db_column='Tester', max_length=10, null=True)),
                ('testcode_1', models.CharField(blank=True, db_column='Testcode 1', max_length=10, null=True)),
                ('testcode_2', models.CharField(blank=True, db_column='Testcode 2', max_length=10, null=True)),
                ('serial_no_field', models.CharField(blank=True, db_column='Serial No.', max_length=8, null=True)),
                ('firmware_version', models.CharField(blank=True, db_column='Firmware Version', max_length=6, null=True)),
                ('retest_freq_months_field', models.IntegerField(blank=True, db_column='Retest Freq. (Months)', null=True)),
                ('user_data_input_order', models.CharField(blank=True, db_column='User Data Input Order', max_length=12, null=True)),
            ],
            options={
                'db_table': 'records',
            },
        ),
        migrations.CreateModel(
            name='ItemDescription',
            fields=[
                ('record_id', models.OneToOneField(db_column='Record ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bts_asset_db.Records')),
                ('asset_description', models.CharField(blank=True, db_column='Asset Description', max_length=20, null=True)),
            ],
            options={
                'db_table': 'item_description',
            },
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('record_id', models.OneToOneField(db_column='Record ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bts_asset_db.Records')),
                ('asset_group', models.CharField(blank=True, db_column='Asset Group', max_length=20, null=True)),
            ],
            options={
                'db_table': 'item_group',
            },
        ),
        migrations.CreateModel(
            name='ItemMake',
            fields=[
                ('record_id', models.OneToOneField(db_column='Record ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bts_asset_db.Records')),
                ('make', models.CharField(blank=True, db_column='Make', max_length=20, null=True)),
            ],
            options={
                'db_table': 'item_make',
            },
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('record_id', models.OneToOneField(db_column='Record ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bts_asset_db.Records')),
                ('model', models.CharField(blank=True, db_column='Model', max_length=20, null=True)),
            ],
            options={
                'db_table': 'item_model',
            },
        ),
        migrations.CreateModel(
            name='ItemNotes',
            fields=[
                ('record_id', models.OneToOneField(db_column='Record ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bts_asset_db.Records')),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=20, null=True)),
            ],
            options={
                'db_table': 'item_notes',
            },
        ),
        migrations.CreateModel(
            name='ItemSerialNumber',
            fields=[
                ('record_id', models.OneToOneField(db_column='Record ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bts_asset_db.Records')),
                ('serial_number', models.CharField(blank=True, db_column='Serial Number', max_length=20, null=True)),
            ],
            options={
                'db_table': 'item_serial_number',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('test_id', models.IntegerField(db_column='Test ID', primary_key=True, serialize=False)),
                ('test_type', models.IntegerField(blank=True, db_column='Test Type', null=True)),
                ('test_parameter_1', models.CharField(blank=True, db_column='Test Parameter 1', max_length=5, null=True)),
                ('test_parameter_2', models.CharField(blank=True, db_column='Test Parameter 2', max_length=18, null=True)),
                ('test_parameter_3', models.CharField(blank=True, db_column='Test Parameter 3', max_length=6, null=True)),
                ('record_id', models.ForeignKey(blank=True, db_column='Record ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bts_asset_db.Records')),
            ],
            options={
                'db_table': 'tests',
            },
        ),
    ]
