# Generated by Django 3.0.3 on 2020-02-18 15:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bts_asset_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('initials', models.CharField(max_length=10)),
                ('pat_level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('vis_level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('machine_name', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisualTests',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('item_id', models.CharField(max_length=15)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'vis_level': 3}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='visual_supervision_set', to='bts_asset_db.Tester')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visual_test_set', to='bts_asset_db.Tester')),
            ],
        ),
        migrations.DeleteModel(
            name='Canary',
        ),
        migrations.RemoveField(
            model_name='records',
            name='retest_freq_months_field',
        ),
        migrations.RemoveField(
            model_name='records',
            name='serial_no_field',
        ),
        migrations.AddField(
            model_name='records',
            name='retest_freq_months',
            field=models.IntegerField(db_column='Retest Freq. (Months)', default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='records',
            name='serial_no',
            field=models.CharField(db_column='Serial No.', default=None, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='records',
            name='firmware_version',
            field=models.CharField(db_column='Firmware Version', default=None, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='records',
            name='item_id',
            field=models.CharField(db_column='Item ID', default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='records',
            name='location',
            field=models.CharField(db_column='Location', default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='records',
            name='site',
            field=models.CharField(db_column='Site', default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='records',
            name='testcode_1',
            field=models.CharField(db_column='Testcode 1', default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='records',
            name='testcode_2',
            field=models.CharField(db_column='Testcode 2', default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='records',
            name='tester',
            field=models.CharField(db_column='Tester', default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='records',
            name='timestamp',
            field=models.DateField(db_column='Timestamp', default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='records',
            name='user_data_input_order',
            field=models.CharField(db_column='User Data Input Order', default=None, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tests',
            name='record_id',
            field=models.ForeignKey(db_column='Record ID', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='bts_asset_db.Records'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tests',
            name='test_type',
            field=models.IntegerField(db_column='Test Type', default=None),
            preserve_default=False,
        ),
    ]
