# Generated by Django 3.0.7 on 2020-09-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts_asset_db', '0002_auto_20200624_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_channel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_consumable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_identifiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_multichannel',
            field=models.BooleanField(default=False),
        ),
    ]
