# Generated by Django 3.0.3 on 2020-02-18 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bts_asset_db', '0002_auto_20200218_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tester',
            name='initials',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='tester',
            field=models.ForeignKey(db_column='Tester', on_delete=django.db.models.deletion.DO_NOTHING, to='bts_asset_db.Tester', to_field='initials'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='records',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bts_asset_db.Item'),
        ),
    ]
