# Generated by Django 3.0.3 on 2020-02-18 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bts_asset_db', '0003_auto_20200218_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='item_id',
            field=models.ForeignKey(db_column='Item ID', on_delete=django.db.models.deletion.DO_NOTHING, to='bts_asset_db.Item'),
        ),
    ]
