# Generated by Django 3.0.7 on 2020-09-02 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bts_asset_db', '0003_auto_20200902_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repair_supervision_set', to='bts_asset_db.Tester'),
        ),
    ]
