# Generated by Django 3.0.7 on 2020-09-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts_asset_db', '0004_auto_20200902_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
