# Generated by Django 3.0.7 on 2020-09-02 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bts_asset_db', '0005_tester_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'archived': False, 'vis_level': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repair_supervision_set', to='bts_asset_db.Tester'),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'archived': False, 'vis_level': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visual_supervision_set', to='bts_asset_db.Tester'),
        ),
    ]
