# Generated by Django 3.0.3 on 2020-02-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts_asset_db', '0005_auto_20200219_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualtests',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
