# Generated by Django 3.0.3 on 2020-03-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts_asset_db', '0006_auto_20200219_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='record_id',
            field=models.AutoField(db_column='Record ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tester',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tests',
            name='test_id',
            field=models.AutoField(db_column='Test ID', primary_key=True, serialize=False),
        ),
    ]
