# Generated by Django 3.0.7 on 2020-09-02 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bts_asset_db', '0006_auto_20200902_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='repairer',
            field=models.ForeignKey(limit_choices_to={'archived': False}, on_delete=django.db.models.deletion.PROTECT, related_name='repair_set', to='bts_asset_db.Tester'),
        ),
        migrations.AlterField(
            model_name='visualtest',
            name='tester',
            field=models.ForeignKey(limit_choices_to={'archived': False}, on_delete=django.db.models.deletion.PROTECT, related_name='visual_test_set', to='bts_asset_db.Tester'),
        ),
    ]
