# Generated by Django 3.0.7 on 2020-10-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts_asset_db', '0007_auto_20200902_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=10)),
                ('last_imported_record_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='item_description',
            field=models.CharField(blank=True, max_length=83, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='item_group',
            field=models.CharField(blank=True, max_length=83, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='item_make',
            field=models.CharField(blank=True, max_length=83, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='item_model',
            field=models.CharField(blank=True, max_length=83, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='item_notes',
            field=models.CharField(blank=True, max_length=83, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='item_serial_number',
            field=models.CharField(blank=True, max_length=83, null=True),
        ),
    ]
