# Generated by Django 3.0.3 on 2020-04-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts_asset_db', '0007_auto_20200327_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='alt_machine_name',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
