# Generated by Django 3.0.7 on 2020-10-09 17:45

from django.db import migrations


def create_pat_testers(apps, schema_editor):
    TestingMachine = apps.get_model('bts_asset_db', 'TestingMachine')

    TestingMachine(serial_number="49A-1045").save()
    TestingMachine(serial_number="T49-0100").save()
    TestingMachine(serial_number="Y49-0892").save()


class Migration(migrations.Migration):

    dependencies = [
        ('bts_asset_db', '0008_auto_20201009_1842'),
    ]

    operations = [
        migrations.RunPython(create_pat_testers)
    ]
