# Generated by Django 3.0.3 on 2020-04-06 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bts_asset_db', '0008_tester_alt_machine_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='itemdescription',
            old_name='record_id',
            new_name='record',
        ),
        migrations.RenameField(
            model_name='itemgroup',
            old_name='record_id',
            new_name='record',
        ),
        migrations.RenameField(
            model_name='itemmake',
            old_name='record_id',
            new_name='record',
        ),
        migrations.RenameField(
            model_name='itemmodel',
            old_name='record_id',
            new_name='record',
        ),
        migrations.RenameField(
            model_name='itemnotes',
            old_name='record_id',
            new_name='record',
        ),
        migrations.RenameField(
            model_name='itemserialnumber',
            old_name='record_id',
            new_name='record',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='record_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='test_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='record_id',
            new_name='record',
        ),
    ]
