# Generated by Django 3.0.3 on 2020-04-07 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bts_asset_db', '0010_auto_20200406_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visualtests',
            old_name='item_id',
            new_name='item',
        ),
        migrations.AddField(
            model_name='visualtests',
            name='failed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Repairs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('failed', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bts_asset_db.Item')),
                ('repairer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='repair_set', to='bts_asset_db.Tester')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='repair_supervision_set', to='bts_asset_db.Tester')),
            ],
        ),
    ]
