# Generated by Django 3.2.25 on 2026-09-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts_asset_db', '0011_importjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='skipped_records',
            field=models.IntegerField(default=0),
        ),
    ]
