# Generated by Django 3.0.3 on 2020-04-08 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bts_asset_db', '0012_auto_20200408_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_multichannel',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemChannel',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(limit_choices_to={'is_multichannel': True}, on_delete=django.db.models.deletion.CASCADE, to='bts_asset_db.Item')),
            ],
        ),
    ]
