# Generated by Django 3.0.3 on 2020-04-08 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bts_asset_db', '0014_auto_20200408_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='associations',
            field=models.ManyToManyField(blank=True, related_name='associated_item_set', to='bts_asset_db.ItemClass'),
        ),
        migrations.RunSQL(
            sql="INSERT INTO `bts_asset_db_owner`(name) VALUES ('Backstage Technical Services')",
            reverse_sql="DELETE FROM `bts_asset_db_owner` WHERE `name` = 'Backstage Technical Services'"
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='bts_asset_db.Owner'),
            preserve_default=False,
        ),
    ]
